[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "~3.11"
jupyterlab = "^4.1.6"
pandas-datareader = "^0.10.0"
yfinance = "^0.2.37"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
